# Test HTTP requests
### use with: REST Client extension

@apiurl = http://localhost:3000/api

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTYsInVzZXJuYW1lIjoibmV3dXNlciIsInVzZXJfbGV2ZWwiOiJyZWd1bGFyIiwiaWF0IjoxNzcyMDkwNDY0LCJleHAiOjE3NzIwOTQwNjR9.4RBtPmB2FcREIOrmn3Teo6wB-b9vmBEuQum08GbD8v4

### GET all items
GET {{apiurl}}/items

### GET item with id 1
GET {{apiurl}}/items/1

### Add new item
POST {{apiurl}}/items
Content-Type: application/json

{"name": "Mandariini", "weight": 86}

### Delete item with id 2
DELETE {{apiurl}}/items/2

### Update item with id 1
PUT {{apiurl}}/items/1
Content-Type: application/json

{"name": "updated Omena"}

###############################
### users endpoint


### Get all users
GET {{apiurl}}/users

### Post login
POST http://localhost:3000/api/auth/login
content-type: application/json

{
  "username": "newuser",
  "password": "securepassword"
}

### Get my user info
GET http://localhost:3000/api/auth/me
Authorization: Bearer {{token}}

### Register new user
POST {{apiurl}}/users
Content-Type: application/json

{
"username": "newuser",
"password": "securepassword",
"email": "newuser@example.com"
}

### Register new user FAIL email missing
POST {{apiurl}}/users
Content-Type: application/json

{"username": "newuser",
"password": "securepassword"}

### Get user by id 1
GET {{apiurl}}/users/1

### Update user by id 13
PUT {{apiurl}}/users/13
Content-Type: application/json

{"username": "updatednewuser",
"email": "newemail@example.com"}

### Delete user by id
DELETE {{apiurl}}/users/14

### User login
POST {{apiurl}}/users/login
Content-Type: application/json

{
 "username": "newuser",
 "password": "securepassword"
}

##############################
### Diary entry endpoints

### Get all entries
GET {{apiurl}}/entries

### Get entry by id
GET {{apiurl}}/entries/6

### Post new entry
POST {{apiurl}}/entries
Content-Type: application/json

{
  "user_id": 3,
  "entry_date": "2026-02-04",
  "mood": "really happy",
  "weight": 66,
  "sleep_hours": 5,
  "notes": "normipäivä"
}
